### PR TITLE
Patrick contrib

### PR DESCRIPTION
**Pull request by Patrick5455**
I created a script that can be useful for web scrapping handles of top twitter influencers of any country and searching for top tweets by hashtags using selenium & google search library

### CODE REVIEW

**Comment by Patrick5455** [comment]
I created a script that can be useful for web scrapping handles of top twitter influencers of any country and searching for top tweets by hashtags using selenium & google search library

**Comment by Patrick5455** [comment]
I created a script that can be useful for web scrapping handles of top twitter influencers of any country and searching for top tweets by hashtags using selenium & google search library

**Review by 10acad — CHANGES_REQUESTED** [review]
Hey, can you remove the data and read a small description to the codes you are contributing?

At bare minimum 
* write what each notebook or code is doing what
* remove any unnecessary file - your reports, data files you used for your submission
* update readme to point where the main code you want other people to use exists

If you have time add the following
* references to where people can read more to understand what your code does e.g. how to use selenium, stackoverflow pages you used
* which functions in the notebook contains the main code

**Comment by Patrick5455** [comment]
> Hey, can you remove the data and read a small description to the codes you are contributing?
> 
> At bare minimum
> 
>     * write what each notebook or code is doing what
> 
>     * remove any unnecessary file - your reports, data files you used for your submission
> 
>     * update readme to point where the main code you want other people to use exists
> 
> 
> If you have time add the following
> 
>     * references to where people can read more to understand what your code does e.g. how to use selenium, StackOverflow pages you used
> 
>     * which functions in the notebook contains the main code

Thank you for the feedback sir. 
I would also like to point out that the particular notebook I requested to be merged is the  `webScrapper.ipynb`.
I will make the appropriate changes. and revert as soon as possible.

**Comment by Patrick5455** [comment]
Hello Yabebal,
I have applied the required changes.
Please accept my pull rquest
Thank you

**Review by 10acad — APPROVED** [review]
Great! This looks nice!

**Review by 10acad — APPROVED** [review]
Great! I like the description now.

**Pull request merged**
